FROM nginx:latest

RUN apt-get update && \
    apt-get install -y certbot python3-certbot-nginx && \
    rm -rf /var/lib/apt/lists/*

COPY nginx.conf /etc/nginx/nginx.conf
COPY certbot-init.sh /certbot-init.sh

RUN chmod +x /certbot-init.sh

CMD ["/bin/bash", "/certbot-init.sh"] 